---
# GitLab CI Job
# Check python files syntax and security

# Docker image based on latest python 3
image: wdhowe/py3tester

stages:
    - build
    - test

build:verify packages:
    # Verify required packages for testing
    stage: build
    script:
        - "which bandit"
        - "which black"

test:script syntax:
    # Check syntax and formatting
    stage: test
    script:
        - "black --check *.py"
        - "black --check unit-tests/*.py"

test:test script security:
    # Check for security issues - warn about them
    stage: test
    allow_failure: true
    script: "bandit --recursive *.py"
...
